// lib/features/life/model/language_curriculum.dart
//
// Hardcoded curriculum: 20 topics (same structure for every language) +
// core vocabulary seeds per language. Lesson content is generated by the AI
// on-demand and cached. The topic list itself never needs an API call.

import 'language_model.dart';

class LanguageCurriculum {
  LanguageCurriculum._();

  // ── 20 universal topics ────────────────────────────────────────────────────
  // Same structure across all 10 languages. The AI service generates
  // language-specific
  // content when the user opens a topic for the first time.

  static List<TopicModel> topicsFor(SupportedLanguage lang) => [
    // ── Phase 1: Foundations (topics 1–4) ────────────────────────────────
    TopicModel(
      order:       1,
      id:          '${lang.name}_t01',
      title:       'Alphabet & Writing System',
      description: 'Learn the script, characters, or alphabet. How sounds map to symbols.',
      phase:       LanguagePhase.foundations,
    ),
    TopicModel(
      order:       2,
      id:          '${lang.name}_t02',
      title:       'Pronunciation & Tones',
      description: 'Master the sounds unique to this language. Mouth position, tone rules.',
      phase:       LanguagePhase.foundations,
    ),
    TopicModel(
      order:       3,
      id:          '${lang.name}_t03',
      title:       'Numbers, Days & Time',
      description: 'Count 1–100. Days of the week. Telling the time.',
      phase:       LanguagePhase.foundations,
    ),
    TopicModel(
      order:       4,
      id:          '${lang.name}_t04',
      title:       'Greetings & Introductions',
      description: 'Hello, goodbye, my name is, where are you from. First real conversation.',
      phase:       LanguagePhase.foundations,
    ),

    // ── Phase 2: Survival (topics 5–8) ───────────────────────────────────
    TopicModel(
      order:       5,
      id:          '${lang.name}_t05',
      title:       'Core 100 Words',
      description: 'The most frequently used words. Nouns, verbs, adjectives you will hear daily.',
      phase:       LanguagePhase.survival,
    ),
    TopicModel(
      order:       6,
      id:          '${lang.name}_t06',
      title:       'Present Tense',
      description: 'Build basic sentences. I am, you have, he wants. Subject + verb patterns.',
      phase:       LanguagePhase.survival,
    ),
    TopicModel(
      order:       7,
      id:          '${lang.name}_t07',
      title:       'Questions & Negations',
      description: 'How to ask: who, what, where, when, why, how. How to say no.',
      phase:       LanguagePhase.survival,
    ),
    TopicModel(
      order:       8,
      id:          '${lang.name}_t08',
      title:       'Food, Shopping & Money',
      description: 'Survive in a restaurant, market, or shop. Prices, ordering, paying.',
      phase:       LanguagePhase.survival,
    ),

    // ── Phase 3: Conversational (topics 9–12) ────────────────────────────
    TopicModel(
      order:       9,
      id:          '${lang.name}_t09',
      title:       'Directions & Places',
      description: 'Navigate cities. Left, right, near, far. Common places: bank, hospital, hotel.',
      phase:       LanguagePhase.conversational,
    ),
    TopicModel(
      order:       10,
      id:          '${lang.name}_t10',
      title:       'Past Tense',
      description: 'Talk about what happened. Yesterday, last week, when I was a child.',
      phase:       LanguagePhase.conversational,
    ),
    TopicModel(
      order:       11,
      id:          '${lang.name}_t11',
      title:       'Future Tense & Plans',
      description: 'Express intentions and plans. Tomorrow, I will, I want to, I hope.',
      phase:       LanguagePhase.conversational,
    ),
    TopicModel(
      order:       12,
      id:          '${lang.name}_t12',
      title:       'Family & Relationships',
      description: 'Family members, describing people, expressing emotions.',
      phase:       LanguagePhase.conversational,
    ),

    // ── Phase 4: Fluency (topics 13–16) ──────────────────────────────────
    TopicModel(
      order:       13,
      id:          '${lang.name}_t13',
      title:       'Work & Daily Life',
      description: 'Jobs, routines, schedules. Talking about your profession and day.',
      phase:       LanguagePhase.fluency,
    ),
    TopicModel(
      order:       14,
      id:          '${lang.name}_t14',
      title:       'Advanced Grammar',
      description: 'Subjunctive, conditionals, complex sentence structures.',
      phase:       LanguagePhase.fluency,
    ),
    TopicModel(
      order:       15,
      id:          '${lang.name}_t15',
      title:       'Idioms & Expressions',
      description: 'Sound like a local. Common phrases, proverbs, informal speech.',
      phase:       LanguagePhase.fluency,
    ),
    TopicModel(
      order:       16,
      id:          '${lang.name}_t16',
      title:       'Reading & Comprehension',
      description: 'Short texts, news snippets, signs. Build reading speed and comprehension.',
      phase:       LanguagePhase.fluency,
    ),

    // ── Phase 5: Near-Native (topics 17–20) ──────────────────────────────
    TopicModel(
      order:       17,
      id:          '${lang.name}_t17',
      title:       'Nuance & Register',
      description: 'Formal vs informal. Polite vs casual. When to use which tone.',
      phase:       LanguagePhase.nativeLevel,
    ),
    TopicModel(
      order:       18,
      id:          '${lang.name}_t18',
      title:       'Cultural Context',
      description: 'Customs, humor, taboos, social norms. What natives assume you know.',
      phase:       LanguagePhase.nativeLevel,
    ),
    TopicModel(
      order:       19,
      id:          '${lang.name}_t19',
      title:       'Listening & Media',
      description: 'Songs, movies, podcasts in the language. Train your ear for native speed.',
      phase:       LanguagePhase.nativeLevel,
    ),
    TopicModel(
      order:       20,
      id:          '${lang.name}_t20',
      title:       'Free Conversation',
      description: 'Open-ended practice. Talk about anything. Full sentences, no scaffolding.',
      phase:       LanguagePhase.nativeLevel,
    ),
  ];

  // ── Core vocabulary seeds per language ────────────────────────────────────
  // 20 words per language as a starter pack.
  // Full vocabulary is generated by the AI service as topics are completed.

  static List<VocabularyItem> vocabularyFor(SupportedLanguage lang) {
    switch (lang) {
      case SupportedLanguage.mandarin:
        return _mandarin;
      case SupportedLanguage.spanish:
        return _spanish;
      case SupportedLanguage.hindi:
        return _hindi;
      case SupportedLanguage.arabic:
        return _arabic;
      case SupportedLanguage.french:
        return _french;
      case SupportedLanguage.portuguese:
        return _portuguese;
      case SupportedLanguage.russian:
        return _russian;
      case SupportedLanguage.japanese:
        return _japanese;
      case SupportedLanguage.english:
        return _english;
      case SupportedLanguage.german:
        return _german;
    }
  }

  // ── Vocabulary seeds ──────────────────────────────────────────────────────

  static const _mandarin = [
    VocabularyItem(word: '你好', translation: 'Hello', phonetic: 'nǐ hǎo', example: '你好，我叫小明。', exampleTranslation: 'Hello, my name is Xiaoming.'),
    VocabularyItem(word: '谢谢', translation: 'Thank you', phonetic: 'xiè xiè', example: '谢谢你的帮助。', exampleTranslation: 'Thank you for your help.'),
    VocabularyItem(word: '水', translation: 'Water', phonetic: 'shuǐ', example: '我想要一杯水。', exampleTranslation: 'I want a glass of water.'),
    VocabularyItem(word: '我', translation: 'I / Me', phonetic: 'wǒ', example: '我是学生。', exampleTranslation: 'I am a student.'),
    VocabularyItem(word: '好', translation: 'Good', phonetic: 'hǎo', example: '今天天气很好。', exampleTranslation: 'The weather is good today.'),
    VocabularyItem(word: '是', translation: 'To be (am/is/are)', phonetic: 'shì', example: '这是我的书。', exampleTranslation: 'This is my book.'),
    VocabularyItem(word: '吃', translation: 'To eat', phonetic: 'chī', example: '我想吃饺子。', exampleTranslation: 'I want to eat dumplings.'),
    VocabularyItem(word: '朋友', translation: 'Friend', phonetic: 'péng yǒu', example: '他是我的好朋友。', exampleTranslation: 'He is my good friend.'),
    VocabularyItem(word: '钱', translation: 'Money', phonetic: 'qián', example: '这个多少钱？', exampleTranslation: 'How much does this cost?'),
    VocabularyItem(word: '今天', translation: 'Today', phonetic: 'jīn tiān', example: '今天是星期一。', exampleTranslation: 'Today is Monday.'),
    VocabularyItem(word: '去', translation: 'To go', phonetic: 'qù', example: '我要去学校。', exampleTranslation: 'I am going to school.'),
    VocabularyItem(word: '大', translation: 'Big', phonetic: 'dà', example: '这个房间很大。', exampleTranslation: 'This room is very big.'),
    VocabularyItem(word: '一', translation: 'One', phonetic: 'yī', example: '我有一个苹果。', exampleTranslation: 'I have one apple.'),
    VocabularyItem(word: '人', translation: 'Person / People', phonetic: 'rén', example: '这里有很多人。', exampleTranslation: 'There are many people here.'),
    VocabularyItem(word: '什么', translation: 'What', phonetic: 'shén me', example: '你叫什么名字？', exampleTranslation: 'What is your name?'),
    VocabularyItem(word: '在', translation: 'To be at / in', phonetic: 'zài', example: '我在家。', exampleTranslation: 'I am at home.'),
    VocabularyItem(word: '有', translation: 'To have', phonetic: 'yǒu', example: '你有手机吗？', exampleTranslation: 'Do you have a phone?'),
    VocabularyItem(word: '不', translation: 'No / Not', phonetic: 'bù', example: '我不知道。', exampleTranslation: 'I do not know.'),
    VocabularyItem(word: '喜欢', translation: 'To like', phonetic: 'xǐ huān', example: '我喜欢音乐。', exampleTranslation: 'I like music.'),
    VocabularyItem(word: '再见', translation: 'Goodbye', phonetic: 'zài jiàn', example: '再见，明天见！', exampleTranslation: 'Goodbye, see you tomorrow!'),
  ];

  static const _spanish = [
    VocabularyItem(word: 'Hola', translation: 'Hello', phonetic: 'OH-lah', example: 'Hola, ¿cómo estás?', exampleTranslation: 'Hello, how are you?'),
    VocabularyItem(word: 'Gracias', translation: 'Thank you', phonetic: 'GRAH-see-as', example: 'Gracias por tu ayuda.', exampleTranslation: 'Thank you for your help.'),
    VocabularyItem(word: 'Agua', translation: 'Water', phonetic: 'AH-gwah', example: 'Quiero un vaso de agua.', exampleTranslation: 'I want a glass of water.'),
    VocabularyItem(word: 'Yo', translation: 'I', phonetic: 'yoh', example: 'Yo soy estudiante.', exampleTranslation: 'I am a student.'),
    VocabularyItem(word: 'Bueno', translation: 'Good', phonetic: 'BWEH-noh', example: 'Hoy hace buen tiempo.', exampleTranslation: 'The weather is good today.'),
    VocabularyItem(word: 'Ser', translation: 'To be (permanent)', phonetic: 'sehr', example: 'Soy de Tanzania.', exampleTranslation: 'I am from Tanzania.'),
    VocabularyItem(word: 'Comer', translation: 'To eat', phonetic: 'koh-MEHR', example: 'Quiero comer tacos.', exampleTranslation: 'I want to eat tacos.'),
    VocabularyItem(word: 'Amigo', translation: 'Friend', phonetic: 'ah-MEE-goh', example: 'Él es mi mejor amigo.', exampleTranslation: 'He is my best friend.'),
    VocabularyItem(word: 'Dinero', translation: 'Money', phonetic: 'dee-NEH-roh', example: '¿Cuánto cuesta esto?', exampleTranslation: 'How much does this cost?'),
    VocabularyItem(word: 'Hoy', translation: 'Today', phonetic: 'oy', example: 'Hoy es lunes.', exampleTranslation: 'Today is Monday.'),
    VocabularyItem(word: 'Ir', translation: 'To go', phonetic: 'eer', example: 'Voy a la escuela.', exampleTranslation: 'I am going to school.'),
    VocabularyItem(word: 'Grande', translation: 'Big', phonetic: 'GRAHN-deh', example: 'Esta habitación es muy grande.', exampleTranslation: 'This room is very big.'),
    VocabularyItem(word: 'Uno', translation: 'One', phonetic: 'OO-noh', example: 'Tengo una manzana.', exampleTranslation: 'I have one apple.'),
    VocabularyItem(word: 'Persona', translation: 'Person', phonetic: 'pehr-SOH-nah', example: 'Hay mucha gente aquí.', exampleTranslation: 'There are many people here.'),
    VocabularyItem(word: '¿Qué?', translation: 'What?', phonetic: 'keh', example: '¿Cómo te llamas?', exampleTranslation: 'What is your name?'),
    VocabularyItem(word: 'Casa', translation: 'Home / House', phonetic: 'KAH-sah', example: 'Estoy en casa.', exampleTranslation: 'I am at home.'),
    VocabularyItem(word: 'Tener', translation: 'To have', phonetic: 'teh-NEHR', example: '¿Tienes un teléfono?', exampleTranslation: 'Do you have a phone?'),
    VocabularyItem(word: 'No', translation: 'No / Not', phonetic: 'noh', example: 'No sé.', exampleTranslation: 'I do not know.'),
    VocabularyItem(word: 'Gustar', translation: 'To like', phonetic: 'goos-TAHR', example: 'Me gusta la música.', exampleTranslation: 'I like music.'),
    VocabularyItem(word: 'Adiós', translation: 'Goodbye', phonetic: 'ah-dee-OHS', example: 'Adiós, ¡hasta mañana!', exampleTranslation: 'Goodbye, see you tomorrow!'),
  ];

  static const _hindi = [
    VocabularyItem(word: 'नमस्ते', translation: 'Hello', phonetic: 'na-mas-teh', example: 'नमस्ते, आप कैसे हैं?', exampleTranslation: 'Hello, how are you?'),
    VocabularyItem(word: 'धन्यवाद', translation: 'Thank you', phonetic: 'dhun-ya-vaad', example: 'आपकी मदद के लिए धन्यवाद।', exampleTranslation: 'Thank you for your help.'),
    VocabularyItem(word: 'पानी', translation: 'Water', phonetic: 'paa-nee', example: 'मुझे एक गिलास पानी चाहिए।', exampleTranslation: 'I want a glass of water.'),
    VocabularyItem(word: 'मैं', translation: 'I', phonetic: 'main', example: 'मैं एक छात्र हूँ।', exampleTranslation: 'I am a student.'),
    VocabularyItem(word: 'अच्छा', translation: 'Good', phonetic: 'ach-cha', example: 'आज मौसम अच्छा है।', exampleTranslation: 'The weather is good today.'),
    VocabularyItem(word: 'खाना', translation: 'Food / To eat', phonetic: 'khaa-naa', example: 'मुझे खाना खाना है।', exampleTranslation: 'I want to eat food.'),
    VocabularyItem(word: 'दोस्त', translation: 'Friend', phonetic: 'dost', example: 'वह मेरा अच्छा दोस्त है।', exampleTranslation: 'He is my good friend.'),
    VocabularyItem(word: 'पैसा', translation: 'Money', phonetic: 'pai-saa', example: 'इसकी कीमत क्या है?', exampleTranslation: 'How much does this cost?'),
    VocabularyItem(word: 'आज', translation: 'Today', phonetic: 'aaj', example: 'आज सोमवार है।', exampleTranslation: 'Today is Monday.'),
    VocabularyItem(word: 'जाना', translation: 'To go', phonetic: 'jaa-naa', example: 'मैं स्कूल जा रहा हूँ।', exampleTranslation: 'I am going to school.'),
    VocabularyItem(word: 'बड़ा', translation: 'Big', phonetic: 'ba-daa', example: 'यह कमरा बहुत बड़ा है।', exampleTranslation: 'This room is very big.'),
    VocabularyItem(word: 'एक', translation: 'One', phonetic: 'ek', example: 'मेरे पास एक सेब है।', exampleTranslation: 'I have one apple.'),
    VocabularyItem(word: 'क्या', translation: 'What?', phonetic: 'kyaa', example: 'आपका नाम क्या है?', exampleTranslation: 'What is your name?'),
    VocabularyItem(word: 'घर', translation: 'Home / House', phonetic: 'ghar', example: 'मैं घर पर हूँ।', exampleTranslation: 'I am at home.'),
    VocabularyItem(word: 'होना', translation: 'To have / To be', phonetic: 'ho-naa', example: 'क्या आपके पास फोन है?', exampleTranslation: 'Do you have a phone?'),
    VocabularyItem(word: 'नहीं', translation: 'No / Not', phonetic: 'na-heen', example: 'मुझे नहीं पता।', exampleTranslation: 'I do not know.'),
    VocabularyItem(word: 'पसंद', translation: 'To like', phonetic: 'pa-sand', example: 'मुझे संगीत पसंद है।', exampleTranslation: 'I like music.'),
    VocabularyItem(word: 'अलविदा', translation: 'Goodbye', phonetic: 'al-vi-daa', example: 'अलविदा, कल मिलते हैं!', exampleTranslation: 'Goodbye, see you tomorrow!'),
    VocabularyItem(word: 'हाँ', translation: 'Yes', phonetic: 'haan', example: 'हाँ, मैं समझता हूँ।', exampleTranslation: 'Yes, I understand.'),
    VocabularyItem(word: 'प्यार', translation: 'Love', phonetic: 'pyaar', example: 'मैं अपने परिवार से प्यार करता हूँ।', exampleTranslation: 'I love my family.'),
  ];

  static const _arabic = [
    VocabularyItem(word: 'مرحبا', translation: 'Hello', phonetic: 'mar-ha-ban', example: 'مرحبا، كيف حالك؟', exampleTranslation: 'Hello, how are you?'),
    VocabularyItem(word: 'شكرا', translation: 'Thank you', phonetic: 'shuk-ran', example: 'شكرا على مساعدتك.', exampleTranslation: 'Thank you for your help.'),
    VocabularyItem(word: 'ماء', translation: 'Water', phonetic: 'maa\'', example: 'أريد كوبًا من الماء.', exampleTranslation: 'I want a glass of water.'),
    VocabularyItem(word: 'أنا', translation: 'I', phonetic: 'a-naa', example: 'أنا طالب.', exampleTranslation: 'I am a student.'),
    VocabularyItem(word: 'جيد', translation: 'Good', phonetic: 'ja-yid', example: 'الطقس جيد اليوم.', exampleTranslation: 'The weather is good today.'),
    VocabularyItem(word: 'أكل', translation: 'To eat', phonetic: 'a-ka-la', example: 'أريد أن آكل.', exampleTranslation: 'I want to eat.'),
    VocabularyItem(word: 'صديق', translation: 'Friend', phonetic: 'sa-deeq', example: 'هو صديقي الجيد.', exampleTranslation: 'He is my good friend.'),
    VocabularyItem(word: 'مال', translation: 'Money', phonetic: 'maal', example: 'كم يكلف هذا؟', exampleTranslation: 'How much does this cost?'),
    VocabularyItem(word: 'اليوم', translation: 'Today', phonetic: 'al-yawm', example: 'اليوم هو الاثنين.', exampleTranslation: 'Today is Monday.'),
    VocabularyItem(word: 'ذهب', translation: 'To go', phonetic: 'dha-ha-ba', example: 'أنا ذاهب إلى المدرسة.', exampleTranslation: 'I am going to school.'),
    VocabularyItem(word: 'كبير', translation: 'Big', phonetic: 'ka-beer', example: 'هذه الغرفة كبيرة جدًا.', exampleTranslation: 'This room is very big.'),
    VocabularyItem(word: 'واحد', translation: 'One', phonetic: 'waa-hid', example: 'لدي تفاحة واحدة.', exampleTranslation: 'I have one apple.'),
    VocabularyItem(word: 'ماذا', translation: 'What?', phonetic: 'maa-dhaa', example: 'ما اسمك؟', exampleTranslation: 'What is your name?'),
    VocabularyItem(word: 'بيت', translation: 'Home / House', phonetic: 'bayt', example: 'أنا في البيت.', exampleTranslation: 'I am at home.'),
    VocabularyItem(word: 'لا', translation: 'No / Not', phonetic: 'laa', example: 'لا أعرف.', exampleTranslation: 'I do not know.'),
    VocabularyItem(word: 'يحب', translation: 'To like / love', phonetic: 'yu-hibb', example: 'أحب الموسيقى.', exampleTranslation: 'I like music.'),
    VocabularyItem(word: 'مع السلامة', translation: 'Goodbye', phonetic: 'ma\'a s-sa-laa-ma', example: 'مع السلامة، إلى اللقاء!', exampleTranslation: 'Goodbye, see you!'),
    VocabularyItem(word: 'نعم', translation: 'Yes', phonetic: 'na\'am', example: 'نعم، أفهم.', exampleTranslation: 'Yes, I understand.'),
    VocabularyItem(word: 'كلب', translation: 'Dog', phonetic: 'kalb', example: 'لدي كلب صغير.', exampleTranslation: 'I have a small dog.'),
    VocabularyItem(word: 'كتاب', translation: 'Book', phonetic: 'ki-taab', example: 'هذا كتابي.', exampleTranslation: 'This is my book.'),
  ];

  static const _french = [
    VocabularyItem(word: 'Bonjour', translation: 'Hello', phonetic: 'bon-ZHOOR', example: 'Bonjour, comment allez-vous?', exampleTranslation: 'Hello, how are you?'),
    VocabularyItem(word: 'Merci', translation: 'Thank you', phonetic: 'mehr-SEE', example: 'Merci pour votre aide.', exampleTranslation: 'Thank you for your help.'),
    VocabularyItem(word: 'Eau', translation: 'Water', phonetic: 'oh', example: 'Je voudrais un verre d\'eau.', exampleTranslation: 'I would like a glass of water.'),
    VocabularyItem(word: 'Je', translation: 'I', phonetic: 'zhuh', example: 'Je suis étudiant.', exampleTranslation: 'I am a student.'),
    VocabularyItem(word: 'Bon', translation: 'Good', phonetic: 'bohn', example: 'Il fait beau aujourd\'hui.', exampleTranslation: 'The weather is good today.'),
    VocabularyItem(word: 'Manger', translation: 'To eat', phonetic: 'mahn-ZHAY', example: 'Je veux manger du pain.', exampleTranslation: 'I want to eat bread.'),
    VocabularyItem(word: 'Ami', translation: 'Friend', phonetic: 'ah-MEE', example: 'Il est mon meilleur ami.', exampleTranslation: 'He is my best friend.'),
    VocabularyItem(word: 'Argent', translation: 'Money', phonetic: 'ar-ZHAHN', example: 'Combien ça coûte?', exampleTranslation: 'How much does it cost?'),
    VocabularyItem(word: "Aujourd'hui", translation: 'Today', phonetic: 'oh-zhoor-DWEE', example: "Aujourd'hui c'est lundi.", exampleTranslation: 'Today is Monday.'),
    VocabularyItem(word: 'Aller', translation: 'To go', phonetic: 'ah-LAY', example: 'Je vais à l\'école.', exampleTranslation: 'I am going to school.'),
    VocabularyItem(word: 'Grand', translation: 'Big', phonetic: 'grahn', example: 'Cette pièce est très grande.', exampleTranslation: 'This room is very big.'),
    VocabularyItem(word: 'Un', translation: 'One / A', phonetic: 'uhn', example: "J'ai une pomme.", exampleTranslation: 'I have one apple.'),
    VocabularyItem(word: 'Quoi', translation: 'What?', phonetic: 'kwah', example: 'Comment tu t\'appelles?', exampleTranslation: 'What is your name?'),
    VocabularyItem(word: 'Maison', translation: 'Home / House', phonetic: 'meh-ZOHN', example: 'Je suis à la maison.', exampleTranslation: 'I am at home.'),
    VocabularyItem(word: 'Avoir', translation: 'To have', phonetic: 'ah-VWAHR', example: 'Tu as un téléphone?', exampleTranslation: 'Do you have a phone?'),
    VocabularyItem(word: 'Non', translation: 'No / Not', phonetic: 'nohn', example: 'Je ne sais pas.', exampleTranslation: 'I do not know.'),
    VocabularyItem(word: 'Aimer', translation: 'To like / love', phonetic: 'eh-MAY', example: "J'aime la musique.", exampleTranslation: 'I like music.'),
    VocabularyItem(word: 'Au revoir', translation: 'Goodbye', phonetic: 'oh ruh-VWAHR', example: 'Au revoir, à demain!', exampleTranslation: 'Goodbye, see you tomorrow!'),
    VocabularyItem(word: 'Oui', translation: 'Yes', phonetic: 'wee', example: 'Oui, je comprends.', exampleTranslation: 'Yes, I understand.'),
    VocabularyItem(word: 'Livre', translation: 'Book', phonetic: 'LEE-vruh', example: 'C\'est mon livre.', exampleTranslation: 'This is my book.'),
  ];

  static const _portuguese = [
    VocabularyItem(word: 'Olá', translation: 'Hello', phonetic: 'oh-LAH', example: 'Olá, como você está?', exampleTranslation: 'Hello, how are you?'),
    VocabularyItem(word: 'Obrigado', translation: 'Thank you', phonetic: 'oh-bree-GAH-doo', example: 'Obrigado pela sua ajuda.', exampleTranslation: 'Thank you for your help.'),
    VocabularyItem(word: 'Água', translation: 'Water', phonetic: 'AH-gwah', example: 'Quero um copo de água.', exampleTranslation: 'I want a glass of water.'),
    VocabularyItem(word: 'Eu', translation: 'I', phonetic: 'EH-oo', example: 'Eu sou estudante.', exampleTranslation: 'I am a student.'),
    VocabularyItem(word: 'Bom', translation: 'Good', phonetic: 'bohn', example: 'O tempo está bom hoje.', exampleTranslation: 'The weather is good today.'),
    VocabularyItem(word: 'Comer', translation: 'To eat', phonetic: 'koh-MEHR', example: 'Quero comer arroz.', exampleTranslation: 'I want to eat rice.'),
    VocabularyItem(word: 'Amigo', translation: 'Friend', phonetic: 'ah-MEE-goo', example: 'Ele é meu melhor amigo.', exampleTranslation: 'He is my best friend.'),
    VocabularyItem(word: 'Dinheiro', translation: 'Money', phonetic: 'din-YAY-roo', example: 'Quanto custa isso?', exampleTranslation: 'How much does this cost?'),
    VocabularyItem(word: 'Hoje', translation: 'Today', phonetic: 'OH-zheh', example: 'Hoje é segunda-feira.', exampleTranslation: 'Today is Monday.'),
    VocabularyItem(word: 'Ir', translation: 'To go', phonetic: 'eer', example: 'Vou para a escola.', exampleTranslation: 'I am going to school.'),
    VocabularyItem(word: 'Grande', translation: 'Big', phonetic: 'GRAHN-jee', example: 'Este quarto é muito grande.', exampleTranslation: 'This room is very big.'),
    VocabularyItem(word: 'Um', translation: 'One / A', phonetic: 'oom', example: 'Tenho uma maçã.', exampleTranslation: 'I have one apple.'),
    VocabularyItem(word: 'O quê', translation: 'What?', phonetic: 'oo KEH', example: 'Qual é o seu nome?', exampleTranslation: 'What is your name?'),
    VocabularyItem(word: 'Casa', translation: 'Home / House', phonetic: 'KAH-zah', example: 'Estou em casa.', exampleTranslation: 'I am at home.'),
    VocabularyItem(word: 'Ter', translation: 'To have', phonetic: 'tehr', example: 'Você tem um telefone?', exampleTranslation: 'Do you have a phone?'),
    VocabularyItem(word: 'Não', translation: 'No / Not', phonetic: 'nownh', example: 'Não sei.', exampleTranslation: 'I do not know.'),
    VocabularyItem(word: 'Gostar', translation: 'To like', phonetic: 'goos-TAHR', example: 'Eu gosto de música.', exampleTranslation: 'I like music.'),
    VocabularyItem(word: 'Tchau', translation: 'Goodbye', phonetic: 'chow', example: 'Tchau, até amanhã!', exampleTranslation: 'Goodbye, see you tomorrow!'),
    VocabularyItem(word: 'Sim', translation: 'Yes', phonetic: 'seeng', example: 'Sim, eu entendo.', exampleTranslation: 'Yes, I understand.'),
    VocabularyItem(word: 'Livro', translation: 'Book', phonetic: 'LEE-vroo', example: 'Este é o meu livro.', exampleTranslation: 'This is my book.'),
  ];

  static const _russian = [
    VocabularyItem(word: 'Привет', translation: 'Hello (informal)', phonetic: 'pri-VYET', example: 'Привет, как дела?', exampleTranslation: 'Hello, how are you?'),
    VocabularyItem(word: 'Спасибо', translation: 'Thank you', phonetic: 'spa-SEE-ba', example: 'Спасибо за помощь.', exampleTranslation: 'Thank you for your help.'),
    VocabularyItem(word: 'Вода', translation: 'Water', phonetic: 'va-DAH', example: 'Дайте мне стакан воды.', exampleTranslation: 'Give me a glass of water.'),
    VocabularyItem(word: 'Я', translation: 'I', phonetic: 'ya', example: 'Я студент.', exampleTranslation: 'I am a student.'),
    VocabularyItem(word: 'Хороший', translation: 'Good', phonetic: 'kha-RO-shiy', example: 'Сегодня хорошая погода.', exampleTranslation: 'The weather is good today.'),
    VocabularyItem(word: 'Есть', translation: 'To eat / To be', phonetic: 'yest\'', example: 'Я хочу есть.', exampleTranslation: 'I want to eat.'),
    VocabularyItem(word: 'Друг', translation: 'Friend', phonetic: 'drook', example: 'Он мой хороший друг.', exampleTranslation: 'He is my good friend.'),
    VocabularyItem(word: 'Деньги', translation: 'Money', phonetic: 'DYEN\'-gi', example: 'Сколько это стоит?', exampleTranslation: 'How much does this cost?'),
    VocabularyItem(word: 'Сегодня', translation: 'Today', phonetic: 'si-VOD-nya', example: 'Сегодня понедельник.', exampleTranslation: 'Today is Monday.'),
    VocabularyItem(word: 'Идти', translation: 'To go', phonetic: 'id-TEE', example: 'Я иду в школу.', exampleTranslation: 'I am going to school.'),
    VocabularyItem(word: 'Большой', translation: 'Big', phonetic: 'bal\'-SHOY', example: 'Эта комната очень большая.', exampleTranslation: 'This room is very big.'),
    VocabularyItem(word: 'Один', translation: 'One', phonetic: 'a-DEEN', example: 'У меня есть одно яблоко.', exampleTranslation: 'I have one apple.'),
    VocabularyItem(word: 'Что', translation: 'What?', phonetic: 'shto', example: 'Как тебя зовут?', exampleTranslation: 'What is your name?'),
    VocabularyItem(word: 'Дом', translation: 'Home / House', phonetic: 'dom', example: 'Я дома.', exampleTranslation: 'I am at home.'),
    VocabularyItem(word: 'Нет', translation: 'No / Not', phonetic: 'nyet', example: 'Я не знаю.', exampleTranslation: 'I do not know.'),
    VocabularyItem(word: 'Любить', translation: 'To like / love', phonetic: 'lyu-BIT\'', example: 'Я люблю музыку.', exampleTranslation: 'I like music.'),
    VocabularyItem(word: 'До свидания', translation: 'Goodbye', phonetic: 'da svi-DA-ni-ya', example: 'До свидания, до завтра!', exampleTranslation: 'Goodbye, see you tomorrow!'),
    VocabularyItem(word: 'Да', translation: 'Yes', phonetic: 'da', example: 'Да, я понимаю.', exampleTranslation: 'Yes, I understand.'),
    VocabularyItem(word: 'Книга', translation: 'Book', phonetic: 'KNEE-ga', example: 'Это моя книга.', exampleTranslation: 'This is my book.'),
    VocabularyItem(word: 'Здравствуйте', translation: 'Hello (formal)', phonetic: 'ZDRA-stvuy-te', example: 'Здравствуйте, чем могу помочь?', exampleTranslation: 'Hello, how can I help?'),
  ];

  static const _japanese = [
    VocabularyItem(word: 'こんにちは', translation: 'Hello', phonetic: 'kon-ni-chi-wa', example: 'こんにちは、お元気ですか？', exampleTranslation: 'Hello, how are you?'),
    VocabularyItem(word: 'ありがとう', translation: 'Thank you', phonetic: 'a-ri-ga-to', example: 'お手伝いありがとうございます。', exampleTranslation: 'Thank you for your help.'),
    VocabularyItem(word: '水', translation: 'Water', phonetic: 'mi-zu', example: '水を一杯ください。', exampleTranslation: 'Please give me a glass of water.'),
    VocabularyItem(word: '私', translation: 'I / Me', phonetic: 'wa-ta-shi', example: '私は学生です。', exampleTranslation: 'I am a student.'),
    VocabularyItem(word: 'いい', translation: 'Good', phonetic: 'i-i', example: '今日はいい天気ですね。', exampleTranslation: 'The weather is good today.'),
    VocabularyItem(word: '食べる', translation: 'To eat', phonetic: 'ta-be-ru', example: 'ラーメンを食べたい。', exampleTranslation: 'I want to eat ramen.'),
    VocabularyItem(word: '友達', translation: 'Friend', phonetic: 'to-mo-da-chi', example: '彼は私の親友です。', exampleTranslation: 'He is my best friend.'),
    VocabularyItem(word: 'お金', translation: 'Money', phonetic: 'o-ka-ne', example: 'これはいくらですか？', exampleTranslation: 'How much does this cost?'),
    VocabularyItem(word: '今日', translation: 'Today', phonetic: 'kyo', example: '今日は月曜日です。', exampleTranslation: 'Today is Monday.'),
    VocabularyItem(word: '行く', translation: 'To go', phonetic: 'i-ku', example: '学校に行きます。', exampleTranslation: 'I am going to school.'),
    VocabularyItem(word: '大きい', translation: 'Big', phonetic: 'o-ki-i', example: 'この部屋はとても大きい。', exampleTranslation: 'This room is very big.'),
    VocabularyItem(word: '一', translation: 'One', phonetic: 'i-chi', example: 'リンゴが一つあります。', exampleTranslation: 'I have one apple.'),
    VocabularyItem(word: '何', translation: 'What?', phonetic: 'na-ni', example: 'お名前は何ですか？', exampleTranslation: 'What is your name?'),
    VocabularyItem(word: '家', translation: 'Home / House', phonetic: 'i-e', example: '私は家にいます。', exampleTranslation: 'I am at home.'),
    VocabularyItem(word: 'いいえ', translation: 'No', phonetic: 'i-i-e', example: 'いいえ、知りません。', exampleTranslation: 'No, I do not know.'),
    VocabularyItem(word: '好き', translation: 'To like', phonetic: 'su-ki', example: '音楽が好きです。', exampleTranslation: 'I like music.'),
    VocabularyItem(word: 'さようなら', translation: 'Goodbye', phonetic: 'sa-yo-na-ra', example: 'さようなら、また明日！', exampleTranslation: 'Goodbye, see you tomorrow!'),
    VocabularyItem(word: 'はい', translation: 'Yes', phonetic: 'ha-i', example: 'はい、わかりました。', exampleTranslation: 'Yes, I understand.'),
    VocabularyItem(word: '本', translation: 'Book', phonetic: 'hon', example: 'これは私の本です。', exampleTranslation: 'This is my book.'),
    VocabularyItem(word: 'すみません', translation: 'Excuse me / Sorry', phonetic: 'su-mi-ma-sen', example: 'すみません、道を教えてください。', exampleTranslation: 'Excuse me, please tell me the way.'),
  ];

  // English vocabulary for Swahili native speakers.
  // Translations are given in Swahili so the learner reads meaning
  // in their own language first.
  static const _english = [
    VocabularyItem(word: 'Hello', translation: 'Habari / Hujambo', phonetic: 'heh-LOH', example: 'Hello, how are you?', exampleTranslation: 'Habari, u hali gani?'),
    VocabularyItem(word: 'Thank you', translation: 'Asante', phonetic: 'THANK yoo', example: 'Thank you for your help.', exampleTranslation: 'Asante kwa msaada wako.'),
    VocabularyItem(word: 'Water', translation: 'Maji', phonetic: 'WAW-ter', example: 'I want a glass of water.', exampleTranslation: 'Nataka glasi ya maji.'),
    VocabularyItem(word: 'I', translation: 'Mimi / Ninataka', phonetic: 'eye', example: 'I am a student.', exampleTranslation: 'Mimi ni mwanafunzi.'),
    VocabularyItem(word: 'Good', translation: 'Nzuri', phonetic: 'good', example: 'The weather is good today.', exampleTranslation: 'Hali ya hewa ni nzuri leo.'),
    VocabularyItem(word: 'To eat', translation: 'Kula', phonetic: 'too EET', example: 'I want to eat rice.', exampleTranslation: 'Nataka kula mchele.'),
    VocabularyItem(word: 'Friend', translation: 'Rafiki', phonetic: 'frend', example: 'He is my good friend.', exampleTranslation: 'Yeye ni rafiki yangu mzuri.'),
    VocabularyItem(word: 'Money', translation: 'Pesa', phonetic: 'MUN-ee', example: 'How much does this cost?', exampleTranslation: 'Hii inagharimu kiasi gani?'),
    VocabularyItem(word: 'Today', translation: 'Leo', phonetic: 'tuh-DAY', example: 'Today is Monday.', exampleTranslation: 'Leo ni Jumatatu.'),
    VocabularyItem(word: 'To go', translation: 'Kwenda', phonetic: 'too GOH', example: 'I am going to school.', exampleTranslation: 'Ninaenda shuleni.'),
    VocabularyItem(word: 'Big', translation: 'Kubwa', phonetic: 'big', example: 'This room is very big.', exampleTranslation: 'Chumba hiki ni kikubwa sana.'),
    VocabularyItem(word: 'One', translation: 'Moja', phonetic: 'wun', example: 'I have one apple.', exampleTranslation: 'Nina tofaa moja.'),
    VocabularyItem(word: 'What', translation: 'Nini / Gani', phonetic: 'wut', example: 'What is your name?', exampleTranslation: 'Jina lako ni nani?'),
    VocabularyItem(word: 'Home', translation: 'Nyumbani', phonetic: 'hohm', example: 'I am at home.', exampleTranslation: 'Niko nyumbani.'),
    VocabularyItem(word: 'No', translation: 'Hapana / La', phonetic: 'noh', example: 'No, I do not know.', exampleTranslation: 'Hapana, sijui.'),
    VocabularyItem(word: 'To like', translation: 'Kupenda', phonetic: 'too LIEK', example: 'I like music.', exampleTranslation: 'Napenda muziki.'),
    VocabularyItem(word: 'Goodbye', translation: 'Kwaheri', phonetic: 'good-BY', example: 'Goodbye, see you tomorrow!', exampleTranslation: 'Kwaheri, tutaonana kesho!'),
    VocabularyItem(word: 'Yes', translation: 'Ndiyo', phonetic: 'yes', example: 'Yes, I understand.', exampleTranslation: 'Ndiyo, naelewa.'),
    VocabularyItem(word: 'Book', translation: 'Kitabu', phonetic: 'book', example: 'This is my book.', exampleTranslation: 'Hiki ni kitabu changu.'),
    VocabularyItem(word: 'Work', translation: 'Kazi', phonetic: 'werk', example: 'I go to work every day.', exampleTranslation: 'Ninaenda kazini kila siku.'),
  ];

  static const _german = [
    VocabularyItem(word: 'Hallo', translation: 'Hello', phonetic: 'HA-lo', example: 'Hallo, wie geht es dir?', exampleTranslation: 'Hello, how are you?'),
    VocabularyItem(word: 'Danke', translation: 'Thank you', phonetic: 'DAHN-ke', example: 'Danke für deine Hilfe.', exampleTranslation: 'Thank you for your help.'),
    VocabularyItem(word: 'Wasser', translation: 'Water', phonetic: 'VAS-ser', example: 'Ich möchte ein Glas Wasser.', exampleTranslation: 'I would like a glass of water.'),
    VocabularyItem(word: 'Ich', translation: 'I', phonetic: 'ikh', example: 'Ich bin Student.', exampleTranslation: 'I am a student.'),
    VocabularyItem(word: 'Gut', translation: 'Good', phonetic: 'goot', example: 'Das Wetter ist heute gut.', exampleTranslation: 'The weather is good today.'),
    VocabularyItem(word: 'Essen', translation: 'To eat / Food', phonetic: 'ES-sen', example: 'Ich möchte Brot essen.', exampleTranslation: 'I want to eat bread.'),
    VocabularyItem(word: 'Freund', translation: 'Friend', phonetic: 'froynd', example: 'Er ist mein bester Freund.', exampleTranslation: 'He is my best friend.'),
    VocabularyItem(word: 'Geld', translation: 'Money', phonetic: 'gelt', example: 'Wie viel kostet das?', exampleTranslation: 'How much does this cost?'),
    VocabularyItem(word: 'Heute', translation: 'Today', phonetic: 'HOY-te', example: 'Heute ist Montag.', exampleTranslation: 'Today is Monday.'),
    VocabularyItem(word: 'Gehen', translation: 'To go', phonetic: 'GAY-en', example: 'Ich gehe zur Schule.', exampleTranslation: 'I am going to school.'),
    VocabularyItem(word: 'Groß', translation: 'Big', phonetic: 'grohs', example: 'Dieses Zimmer ist sehr groß.', exampleTranslation: 'This room is very big.'),
    VocabularyItem(word: 'Eins', translation: 'One', phonetic: 'ayns', example: 'Ich habe einen Apfel.', exampleTranslation: 'I have one apple.'),
    VocabularyItem(word: 'Was', translation: 'What?', phonetic: 'vas', example: 'Wie heißt du?', exampleTranslation: 'What is your name?'),
    VocabularyItem(word: 'Zuhause', translation: 'Home', phonetic: 'tsoo-HOW-ze', example: 'Ich bin zuhause.', exampleTranslation: 'I am at home.'),
    VocabularyItem(word: 'Haben', translation: 'To have', phonetic: 'HA-ben', example: 'Hast du ein Telefon?', exampleTranslation: 'Do you have a phone?'),
    VocabularyItem(word: 'Nein', translation: 'No / Not', phonetic: 'nayn', example: 'Ich weiß nicht.', exampleTranslation: 'I do not know.'),
    VocabularyItem(word: 'Mögen', translation: 'To like', phonetic: 'MÖ-gen', example: 'Ich mag Musik.', exampleTranslation: 'I like music.'),
    VocabularyItem(word: 'Auf Wiedersehen', translation: 'Goodbye', phonetic: 'owf VEE-der-zayn', example: 'Auf Wiedersehen, bis morgen!', exampleTranslation: 'Goodbye, see you tomorrow!'),
    VocabularyItem(word: 'Ja', translation: 'Yes', phonetic: 'ya', example: 'Ja, ich verstehe.', exampleTranslation: 'Yes, I understand.'),
    VocabularyItem(word: 'Buch', translation: 'Book', phonetic: 'bookh', example: 'Das ist mein Buch.', exampleTranslation: 'This is my book.'),
  ];
}
